### PR TITLE
Logs for get layer by polygon endpoint

### PR DESCRIPTION
**Pull request by ManuelStardust**
## 🛠️ Changes
- Add config for logs.
- Add logs for an endpoint.

## 📝 Associated issues
#11

### CODE REVIEW

**Comment by cazapatamar** [comment]
Please include de 400 errors in the log and create the `logs` dir

**Review by cazapatamar — CHANGES_REQUESTED** [review]
Please include de 400 errors in the log and create the `logs` dir

**Comment by erikasv** [comment]
logs folder must be outside app

**Comment by cazapatamar** [comment]
It is now logging 422 errors, but not 400 errors.

imagen

**Comment by ManuelStardust** [comment]
> It is now logging 422 errors, but not 400 errors.
> 
> imagen

Fixed

**Comment by ManuelStardust** [comment]
> logs folder must be outside app

Done

**Comment by cazapatamar** [comment]
> > logs folder must be outside app
> 
> Done

It is now working!

**Review by cazapatamar — APPROVED** [review]

**Pull request merged**
